"""add user_id to example table

Revision ID: 34fcf60027e9
Revises: 96fb47962c6a
Create Date: 2025-09-03 20:42:01.577515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fcf60027e9'
down_revision: Union[str, None] = '96fb47962c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('user_id', sa.UUID(), nullable=True, comment='User ID from Supabase auth.users'))
    op.create_index(op.f('ix_example_user_id'), 'example', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_user_id'), table_name='example')
    op.drop_column('example', 'user_id')
    # ### end Alembic commands ###
